export const GET_PRODUCT_CATEGORIES_LIST_REQUEST = 'GET_PRODUCT_CATEGORIES_LIST_REQUEST';
export const GET_PRODUCT_CATEGORIES_LIST_LOADING = 'GET_PRODUCT_CATEGORIES_LIST_LOADING';
export const GET_PRODUCT_CATEGORIES_LIST_SUCCESS = 'GET_PRODUCT_CATEGORIES_LIST_SUCCESS';
export const GET_PRODUCT_CATEGORIES_LIST_ERROR = 'GET_PRODUCT_CATEGORIES_LIST_ERROR';
export const GET_PRODUCT_CATEGORIES_LIST_RESET = 'GET_PRODUCT_CATEGORIES_LIST_RESET';

export const CREATE_PRODUCT_CATEGORY_REQUEST = 'CREATE_PRODUCT_CATEGORY_REQUEST';
export const CREATE_PRODUCT_CATEGORY_LOADING = 'CREATE_PRODUCT_CATEGORY_LOADING';
export const CREATE_PRODUCT_CATEGORY_SUCCESS = 'CREATE_PRODUCT_CATEGORY_SUCCESS';
export const CREATE_PRODUCT_CATEGORY_ERROR = 'CREATE_PRODUCT_CATEGORY_ERROR';
export const CREATE_PRODUCT_CATEGORY_RESET = 'CREATE_PRODUCT_CATEGORY_RESET';

export const DELETE_PRODUCT_CATEGORY_REQUEST = 'DELETE_PRODUCT_CATEGORY_REQUEST';
export const DELETE_PRODUCT_CATEGORY_LOADING = 'DELETE_PRODUCT_CATEGORY_LOADING';
export const DELETE_PRODUCT_CATEGORY_SUCCESS = 'DELETE_PRODUCT_CATEGORY_SUCCESS';
export const DELETE_PRODUCT_CATEGORY_ERROR = 'DELETE_PRODUCT_CATEGORY_ERROR';
export const DELETE_PRODUCT_CATEGORY_RESET = 'DELETE_PRODUCT_CATEGORY_RESET';

export const UPDATE_PRODUCT_CATEGORY_REQUEST = 'UPDATE_PRODUCT_CATEGORY_REQUEST';
export const UPDATE_PRODUCT_CATEGORY_LOADING = 'UPDATE_PRODUCT_CATEGORY_LOADING';
export const UPDATE_PRODUCT_CATEGORY_SUCCESS = 'UPDATE_PRODUCT_CATEGORY_SUCCESS';
export const UPDATE_PRODUCT_CATEGORY_ERROR = 'UPDATE_PRODUCT_CATEGORY_ERROR';
export const UPDATE_PRODUCT_CATEGORY_RESET = 'UPDATE_PRODUCT_CATEGORY_RESET';



