export const GET_INVOICES_LIST_REQUEST = 'GET_INVOICES_LIST_REQUEST';
export const GET_INVOICES_LIST_LOADING = 'GET_INVOICES_LIST_LOADING';
export const GET_INVOICES_LIST_SUCCESS = 'GET_INVOICES_LIST_SUCCESS';
export const GET_INVOICES_LIST_ERROR = 'GET_INVOICES_LIST_ERROR';
export const GET_INVOICES_LIST_RESET = 'GET_INVOICES_LIST_RESET';

export const CREATE_INVOICE_REQUEST = 'CREATE_INVOICE_REQUEST';
export const CREATE_INVOICE_LOADING = 'CREATE_INVOICE_LOADING';
export const CREATE_INVOICE_SUCCESS = 'CREATE_INVOICE_SUCCESS';
export const CREATE_INVOICE_ERROR = 'CREATE_INVOICE_ERROR';
export const CREATE_INVOICE_RESET = 'CREATE_INVOICE_RESET';

export const DELETE_INVOICE_REQUEST = 'DELETE_INVOICE_REQUEST';
export const DELETE_INVOICE_LOADING = 'DELETE_INVOICE_LOADING';
export const DELETE_INVOICE_SUCCESS = 'DELETE_INVOICE_SUCCESS';
export const DELETE_INVOICE_ERROR = 'DELETE_INVOICE_ERROR';
export const DELETE_INVOICE_RESET = 'DELETE_INVOICE_RESET';

export const UPDATE_INVOICE_REQUEST = 'UPDATE_INVOICE_REQUEST';
export const UPDATE_INVOICE_LOADING = 'UPDATE_INVOICE_LOADING';
export const UPDATE_INVOICE_SUCCESS = 'UPDATE_INVOICE_SUCCESS';
export const UPDATE_INVOICE_ERROR = 'UPDATE_INVOICE_ERROR';
export const UPDATE_INVOICE_RESET = 'UPDATE_INVOICE_RESET';


export const UPDATE_INVOICE_STATUS_REQUEST = 'UPDATE_INVOICE_STATUS_REQUEST';
export const UPDATE_INVOICE_STATUS_LOADING = 'UPDATE_INVOICE_STATUS_LOADING';
export const UPDATE_INVOICE_STATUS_SUCCESS = 'UPDATE_INVOICE_STATUS_SUCCESS';
export const UPDATE_INVOICE_STATUS_ERROR = 'UPDATE_INVOICE_STATUS_ERROR';
export const UPDATE_INVOICE_STATUS_RESET = 'UPDATE_INVOICE_STATUS_RESET';
