export const GET_STATS_LIST_REQUEST = 'GET_STATS_LIST_REQUEST';
export const GET_STATS_LIST_LOADING = 'GET_STATS_LIST_LOADING';
export const GET_STATS_LIST_SUCCESS = 'GET_STATS_LIST_SUCCESS';
export const GET_STATS_LIST_ERROR = 'GET_STATS_LIST_ERROR';
export const GET_STATS_LIST_RESET = 'GET_STATS_LIST_RESET';