export const GET_INTERNAL_ASSETS_LIST_REQUEST = 'GET_INTERNAL_ASSETS_LIST_REQUEST';
export const GET_INTERNAL_ASSETS_LIST_LOADING = 'GET_INTERNAL_ASSETS_LIST_LOADING';
export const GET_INTERNAL_ASSETS_LIST_SUCCESS = 'GET_INTERNAL_ASSETS_LIST_SUCCESS';
export const GET_INTERNAL_ASSETS_LIST_ERROR = 'GET_INTERNAL_ASSETS_LIST_ERROR';
export const GET_INTERNAL_ASSETS_LIST_RESET = 'GET_INTERNAL_ASSETS_LIST_RESET';

export const GET_ALL_TYPES_LIST_REQUEST = 'GET_ALL_TYPES_LIST_REQUEST';
export const GET_ALL_TYPES_LIST_LOADING = 'GET_ALL_TYPES_LIST_LOADING';
export const GET_ALL_TYPES_LIST_SUCCESS = 'GET_ALL_TYPES_LIST_SUCCESS';
export const GET_ALL_TYPES_LIST_ERROR = 'GET_ALL_TYPES_LIST_ERROR';
export const GET_ALL_TYPES_LIST_RESET = 'GET_ALL_TYPES_LIST_RESET';



export const CREATE_INTERNAL_ASSET_REQUEST = 'CREATE_INTERNAL_ASSET_REQUEST';
export const CREATE_INTERNAL_ASSET_LOADING = 'CREATE_INTERNAL_ASSET_LOADING';
export const CREATE_INTERNAL_ASSET_SUCCESS = 'CREATE_INTERNAL_ASSET_SUCCESS';
export const CREATE_INTERNAL_ASSET_ERROR = 'CREATE_INTERNAL_ASSET_ERROR';
export const CREATE_INTERNAL_ASSET_RESET = 'CREATE_INTERNAL_ASSET_RESET';

export const DELETE_INTERNAL_ASSET_REQUEST = 'DELETE_INTERNAL_ASSET_REQUEST';
export const DELETE_INTERNAL_ASSET_LOADING = 'DELETE_INTERNAL_ASSET_LOADING';
export const DELETE_INTERNAL_ASSET_SUCCESS = 'DELETE_INTERNAL_ASSET_SUCCESS';
export const DELETE_INTERNAL_ASSET_ERROR = 'DELETE_INTERNAL_ASSET_ERROR';
export const DELETE_INTERNAL_ASSET_RESET = 'DELETE_INTERNAL_ASSET_RESET';

export const UPDATE_INTERNAL_ASSET_STATUS_REQUEST = 'UPDATE_INTERNAL_ASSET_STATUS_REQUEST';
export const UPDATE_INTERNAL_ASSET_STATUS_LOADING = 'UPDATE_INTERNAL_ASSET_STATUS_LOADING';
export const UPDATE_INTERNAL_ASSET_STATUS_SUCCESS = 'UPDATE_INTERNAL_ASSET_STATUS_SUCCESS';
export const UPDATE_INTERNAL_ASSET_STATUS_ERROR = 'UPDATE_INTERNAL_ASSET_STATUS_ERROR';
export const UPDATE_INTERNAL_ASSET_STATUS_RESET = 'UPDATE_INTERNAL_ASSET_STATUS_RESET';


export const VIEW_ALL_REQUESTS_ASSETS_REQUEST = 'VIEW_ALL_REQUESTS_ASSETS_REQUEST';
export const VIEW_ALL_REQUESTS_ASSETS_LOADING = 'VIEW_ALL_REQUESTS_ASSETS_LOADING';
export const VIEW_ALL_REQUESTS_ASSETS_SUCCESS = 'VIEW_ALL_REQUESTS_ASSETS_SUCCESS';
export const VIEW_ALL_REQUESTS_ASSETS_ERROR = 'VIEW_ALL_REQUESTS_ASSETS_ERROR';
export const VIEW_ALL_REQUESTS_ASSETS_RESET = 'VIEW_ALL_REQUESTS_ASSETS_RESET';
