export const GET_VENDORS_LIST_REQUEST = 'GET_VENDORS_LIST_REQUEST';
export const GET_VENDORS_LIST_LOADING = 'GET_VENDORS_LIST_LOADING';
export const GET_VENDORS_LIST_SUCCESS = 'GET_VENDORS_LIST_SUCCESS';
export const GET_VENDORS_LIST_ERROR = 'GET_VENDORS_LIST_ERROR';
export const GET_VENDORS_LIST_RESET = 'GET_VENDORS_LIST_RESET';