export const GET_VENDORS_LIST_REQUEST = 'GET_VENDORS_LIST_REQUEST';
export const GET_VENDORS_LIST_LOADING = 'GET_VENDORS_LIST_LOADING';
export const GET_VENDORS_LIST_SUCCESS = 'GET_VENDORS_LIST_SUCCESS';
export const GET_VENDORS_LIST_ERROR = 'GET_VENDORS_LIST_ERROR';
export const GET_VENDORS_LIST_RESET = 'GET_VENDORS_LIST_RESET';

export const CREATE_VENDOR_REQUEST = 'CREATE_VENDOR_REQUEST';
export const CREATE_VENDOR_LOADING = 'CREATE_VENDOR_LOADING';
export const CREATE_VENDOR_SUCCESS = 'CREATE_VENDOR_SUCCESS';
export const CREATE_VENDOR_ERROR = 'CREATE_VENDOR_ERROR';
export const CREATE_VENDOR_RESET = 'CREATE_VENDOR_RESET';

export const DELETE_VENDOR_REQUEST = 'DELETE_VENDOR_REQUEST';
export const DELETE_VENDOR_LOADING = 'DELETE_VENDOR_LOADING';
export const DELETE_VENDOR_SUCCESS = 'DELETE_VENDOR_SUCCESS';
export const DELETE_VENDOR_ERROR = 'DELETE_VENDOR_ERROR';
export const DELETE_VENDOR_RESET = 'DELETE_VENDOR_RESET';

export const UPDATE_VENDOR_REQUEST = 'UPDATE_VENDOR_REQUEST';
export const UPDATE_VENDOR_LOADING = 'UPDATE_VENDOR_LOADING';
export const UPDATE_VENDOR_SUCCESS = 'UPDATE_VENDOR_SUCCESS';
export const UPDATE_VENDOR_ERROR = 'UPDATE_VENDOR_ERROR';
export const UPDATE_VENDOR_RESET = 'UPDATE_VENDOR_RESET';
