export const GET_VENDORS_LIST_REQUEST = 'GET_VENDORS_LIST_REQUEST';
export const GET_VENDORS_LIST_LOADING = 'GET_VENDORS_LIST_LOADING';
export const GET_VENDORS_LIST_SUCCESS = 'GET_VENDORS_LIST_SUCCESS';
export const GET_VENDORS_LIST_ERROR = 'GET_VENDORS_LIST_ERROR';
export const GET_VENDORS_LIST_RESET = 'GET_VENDORS_LIST_RESET';

export const CREATE_VENDOR_REQUEST = 'CREATE_VENDOR_REQUEST';
export const CREATE_VENDOR_LOADING = 'CREATE_VENDOR_LOADING';
export const CREATE_VENDOR_SUCCESS = 'CREATE_VENDOR_SUCCESS';
export const CREATE_VENDOR_ERROR = 'CREATE_VENDOR_ERROR';
export const CREATE_VENDOR_RESET = 'CREATE_VENDOR_RESET';