export const GET_DRIVERS_LIST_REQUEST = 'GET_DRIVERS_LIST_REQUEST';
export const GET_DRIVERS_LIST_LOADING = 'GET_DRIVERS_LIST_LOADING';
export const GET_DRIVERS_LIST_SUCCESS = 'GET_DRIVERS_LIST_SUCCESS';
export const GET_DRIVERS_LIST_ERROR = 'GET_DRIVERS_LIST_ERROR';
export const GET_DRIVERS_LIST_RESET = 'GET_DRIVERS_LIST_RESET';

export const CREATE_DRIVER_REQUEST = 'CREATE_DRIVER_REQUEST';
export const CREATE_DRIVER_LOADING = 'CREATE_DRIVER_LOADING';
export const CREATE_DRIVER_SUCCESS = 'CREATE_DRIVER_SUCCESS';
export const CREATE_DRIVER_ERROR = 'CREATE_DRIVER_ERROR';
export const CREATE_DRIVER_RESET = 'CREATE_DRIVER_RESET';

export const DELETE_DRIVER_REQUEST = 'DELETE_DRIVER_REQUEST';
export const DELETE_DRIVER_LOADING = 'DELETE_DRIVER_LOADING';
export const DELETE_DRIVER_SUCCESS = 'DELETE_DRIVER_SUCCESS';
export const DELETE_DRIVER_ERROR = 'DELETE_DRIVER_ERROR';
export const DELETE_DRIVER_RESET = 'DELETE_DRIVER_RESET';

export const UPDATE_DRIVER_REQUEST = 'UPDATE_DRIVER_REQUEST';
export const UPDATE_DRIVER_LOADING = 'UPDATE_DRIVER_LOADING';
export const UPDATE_DRIVER_SUCCESS = 'UPDATE_DRIVER_SUCCESS';
export const UPDATE_DRIVER_ERROR = 'UPDATE_DRIVER_ERROR';
export const UPDATE_DRIVER_RESET = 'UPDATE_DRIVER_RESET';
