export const COMPANY_REQUEST_ASSET_REQUEST = 'COMPANY_REQUEST_ASSET_REQUEST';
export const COMPANY_REQUEST_ASSET_LOADING = 'COMPANY_REQUEST_ASSET_LOADING';
export const COMPANY_REQUEST_ASSET_SUCCESS = 'COMPANY_REQUEST_ASSET_SUCCESS';
export const COMPANY_REQUEST_ASSET_ERROR = 'COMPANY_REQUEST_ASSET_ERROR';
export const COMPANY_REQUEST_ASSET_RESET = 'COMPANY_REQUEST_ASSET_RESET';


export const INDIVIDUAL_REQUEST_ASSET_REQUEST = 'INDIVIDUAL_REQUEST_ASSET_REQUEST';
export const INDIVIDUAL_REQUEST_ASSET_LOADING = 'INDIVIDUAL_REQUEST_ASSET_LOADING';
export const INDIVIDUAL_REQUEST_ASSET_SUCCESS = 'INDIVIDUAL_REQUEST_ASSET_SUCCESS';
export const INDIVIDUAL_REQUEST_ASSET_ERROR = 'INDIVIDUAL_REQUEST_ASSET_ERROR';
export const INDIVIDUAL_REQUEST_ASSET_RESET = 'INDIVIDUAL_REQUEST_ASSET_RESET';